### ISSUE TITLE
Missing Apollo Client + React Native application files

### ISSUE THREAD

**Issue by geirman** [dabit3/apollo-graphql-mongodb#1]
the article says...

> To begin, we will be having two main projects:
> 1. Apollo Server
> 2. Apollo Client + React Native application

But I only see the server right now.

**Comment by dabit3** [comment]
@geirman yes, the Client is part two, I should have it published by Monday!

**Comment by dabit3** [comment]
@geirman just published this last night. https://medium.com/@dabit3/react-native-with-apollo-part-2-apollo-client-8b4ad4915cf5#.g0gadbv3i Thanks for your feedback on all of this, much appreciated!

**Comment by geirman** [comment]
Can't wait! I'll let you know
