### ISSUE TITLE
Error:  message: Unknown operation named null

### ISSUE THREAD

**Issue by geirman** [dabit3/apollo-graphql-mongodb#2]
Not yet clear what the problem is, but at the end of this tutorial, when I run the GraphQL query...

``` javascript
{
  president(name: "Bill Clinton") {
    name
    term
    party
  }
}
```

I'm getting this error response, sometimes after a significant lag where all I see is a spinner. 

``` javascript
 {
  "errors": [
    {
      "message": "Unknown operation named \"null\"."
    }
  ]
}
```

I've copy/pasted the code for each file to ensure I didn't inadvertently add a typo.

**Comment by geirman** [comment]
May have something to do with the Mongoose setup because [this line](https://github.com/dabit3/apollo-graphql-mongodb-react-native/blob/medium/apolloserver/seed.js#L18) is never executed. I verified that `d` and `president` variables contain the proper data, but it's not saving. I tried modifying the function as follows but nothing.

``` javascript
      data.forEach((d) => {
        const president = new President(d);
        president.save((err, item) => {
          if(!err){
            console.log('saved:', item);
          }else{
            console.log('errored', err);
          }
        });
      });
```

**Comment by dabit3** [comment]
Hmm, if you clone the repo does it give you the same error? @geirman

**Comment by geirman** [comment]
not sure why I didn't notice this before... just not paying close enough attention I guess. I'll use the excuse that it was the end of the day too. Ha! But I get the same results when cloning the repo. After I run `node app.js` I get this error...

> UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: failed to connect to server [localhost:27017] on first connect

once I got my mongodb instance running, I was good to go.

**Comment by geirman** [comment]
BTW, you might want to add something about ensuring you have mongodb running to your setup.

**Comment by dabit3** [comment]
Oh wow I thought it was in there, nice catch! I'm updating now..
